### ISSUE TITLE
Feature Request: Support MongoDB as a database type

### ISSUE THREAD

**Issue by overkidding** [jonesdevelopment/sonar#170] opened 2024-01-23 10:07 UTC
### Information

I think that adding MongoDB as a supported database too could be a good idea.

### Reason

Not everyone uses MySQL as their primary db and some don't even have it installed (like me) to save verified players i think it would be good to add it

**Comment by jonesdevelopment** [comment] 2024-01-23 12:54
Duplicate of https://github.com/jonesdevelopment/sonar/issues/141 — I added MongoDB as an additional database type.

**Closed as completed by jonesdevelopment** 2024-01-23 12:54 UTC
Labels: enhancement
